/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.GUI;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import prodsys.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Neto
 */
public class ProdSysGui extends javax.swing.JFrame {
    public ArrayList<Projeto> projects;
    public HashMap<String,Colaborador>collabs ;
    public ArrayList<Publicação> publications;
    public ArrayList<String> orientations;
    /**
     * Creates new form ProdSysGui
     */
    public ProdSysGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Productivity System"));

        jLabel1.setText("Nome");

        jLabel2.setText("E-mail");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Aluno de Graduação", "Aluno de Mestrado", "Aluno de Doutorado","Pesquisador" }));

        jButton1.setText("Criar Colaborador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Apagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Criar Projeto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Alterar Informação");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Add Publicação(sem projeto)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Add Orientação");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Alterar Estado");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Procurar Colaborador");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Procurar Projeto");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Relatório do Laboratório");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jTextField1))
                                .addGap(49, 49, 49)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String option = (String)jComboBox1.getSelectedItem();
        if(!this.collabs.containsKey(jTextField1.getText())) {
         Colaborador novo ;
        switch (option) {
            case "Professor":
                novo = new Professor(jTextField1.getText(),jTextField2.getText());
                break;
            case "Aluno de Graduação":
                novo = new AlunoDeGraduação(jTextField1.getText(),jTextField2.getText());
                break;
            default:
                novo =new Colaborador(jTextField1.getText(),jTextField2.getText());
                break;
        }
        collabs.put(novo.getName(),novo);
        JOptionPane.showMessageDialog(null,novo.getName() + " Foi criado");
        }
        else  {
            JOptionPane.showMessageDialog(null,"Este colaborador já existe");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ProjetoGUI pg = new ProjetoGUI();
        pg.projetos = this.projects;
        pg.colaboradores = this.collabs;
        pg.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    private int search_project(String nome) {
      int t = this.projects.size();
      for(int i = 0 ; i <t ; i ++) {
          if(projects.get(i).getName().equals(nome)) {
              return i;
          }
      }
      return -1;
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         String nome =   JOptionPane.showInputDialog("Nome do Projeto?");
         int index = search_project(nome);
         if(index==-1) {
             JOptionPane.showMessageDialog(null,"Este projeto não existe");
         } else {
             if(projects.get(index).getClass().equals(Desenvolvimento.class)) {
                String dec = JOptionPane.showInputDialog("Remover colaborador/Adicionar Colaborador");
             String colab = JOptionPane.showInputDialog("Nome do colaborador :");
             dec = dec.toLowerCase();
             if(dec.equals("remover")) {
                 if(((Desenvolvimento)projects.get(index)).contem(colab)) {
                     ((Desenvolvimento)projects.get(index)).removeColaborador(((Desenvolvimento)projects.get(index)).indice(colab));
                     collabs.get(colab).remvProjeto((Desenvolvimento)projects.get(index));
                 }
             } else if(dec.equals("adicionar")) {
                 if(collabs.containsKey(colab)) {
                ((Desenvolvimento)projects.get(index)).addColaborador(this.collabs.get(colab));
                this.collabs.get(colab).addProjeto((Desenvolvimento)projects.get(index));
                 } else {
                     JOptionPane.showMessageDialog(null, colab + "Não existe");
                 }
             }
             } else if(projects.get(index).getClass().equals(Andamento.class)) {
              String numero =   JOptionPane.showInputDialog("Quantos autores a publicação terá?");
              try {
                  int n =Integer.parseInt(numero);
                  ArrayList<String> aut = new ArrayList<>();
                  for(int i = 0 ; i < n ; i ++) {
                      aut.add(JOptionPane.showInputDialog("diga o nome do autor "+ (n-i) + " faltando"));
                  }
                  String obj = JOptionPane.showInputDialog("Diga o conteudo da publicação");
                  Publicação pub = new Publicação(obj,aut);
                  ((Andamento)projects.get(index)).addPub(pub);
                  this.publications.add(pub);
                  for(int i = 0 ; i < aut.size() ; i++) {
                      collabs.get(aut.get(i)).addPub(pub);
                  }
              }catch(NumberFormatException e) {
                  JOptionPane.showMessageDialog(null,"Número inválido");
              }
             }
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nome = JOptionPane.showInputDialog("Nome do Projeto");
        int index = this.search_project(nome);
        if(projects.get(index).getClass().equals(Desenvolvimento.class)) {
        Desenvolvimento desen = (Desenvolvimento)this.projects.get(index);
        if(desen.paraAndamento()) {
        projects.remove(index);
        //pegar data do inicio
        String data = JOptionPane.showInputDialog("Data de início (dia/mes/ano)");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Calendar day = Calendar.getInstance();
                day.setTime(sdf.parse(data));
                Andamento proj =new Andamento(desen.getName(),desen.getMoney(),desen.getAgency(),desen.getObjective(),desen.getDescription(),desen.getCollabs(),day);
                projects.add(proj);
                for(int i = 0 ; i < desen.getCollabs().size();i++) {
                    desen.getCollab(i).remvProjeto(desen);
                    desen.getCollab(i).addProjeto(proj);
                }
            } catch (ParseException ex) {
                
                JOptionPane.showMessageDialog(null,"Formato inválido , tente o formato dia/mes/ano , exemplo : 01/05/2010");
                Logger.getLogger(ProdSysGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não pode alterar estado pois um Aluno de Graduação ja esta em um projeto em Andamento");
        }
        } else if(projects.get(index).getClass().equals(Andamento.class)) {
            if(((Andamento)projects.get(index)).getPubSize()!=0) {
                Andamento and = (Andamento)projects.get(index);
                projects.remove(index);
                //pegar data do fim
                String data = JOptionPane.showInputDialog("Data de término (dia/mes/ano)");
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    Calendar day = Calendar.getInstance();
                    day.setTime(sdf.parse(data));
                    Concluido proj = new Concluido(and.getName(),and.getMoney(),and.getAgency(),and.getObjective(),and.getDescription(),and.getCollabs(),and.getPubs(),day,and.getStart());
                     projects.add(proj);
                     for(int i = 0 ; i < and.getCollabs().size();i++) {
                         and.getCollab(i).remvProjeto(and);
                         and.getCollab(i).addProjeto(proj);
                     }
                }catch(ParseException ex) {
                    JOptionPane.showMessageDialog(null,"Formato inválido , tente o formato dia/mes/ano , exemplo : 01/05/2010");
                    Logger.getLogger(ProdSysGui.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            } else {
                JOptionPane.showMessageDialog(null,"Não pode alterar estado pois faltam publicações ligadas ao projeto antes de finalizar");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
    private int Search_By_State(int st) {
        int t = projects.size(),n=0;
        for(int i = 0 ; i < t ; i ++) {
            if(st==1&&projects.get(i).getClass().equals(Desenvolvimento.class)) {
                n++;
            }
            else if(st==2&&projects.get(i).getClass().equals(Andamento.class)) {
                n++;
            }
            else if(st==3&& projects.get(i).getClass().equals(Concluido.class)) {
                n++;
            }
        } 
        return n;
    }
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String s = "";
        int t;
        s = s + "Colaboradores : " + collabs.size()+"\n";
        s = s + "Desenvolvimento : " + Search_By_State(1)+"\n";
        s = s + "Em Andamento : " + Search_By_State(2)+"\n";
        s = s + "Concluidos : " + Search_By_State(3)+"\n";
        s = s + "Projetos : " + projects.size()+"\n";
        s = s + "Publicações : " + this.publications.size() + "\n";
        s = s + "Orientações : " + this.orientations.size()+"\n";
        JOptionPane.showMessageDialog(null,s);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      try {
          ArrayList<String>authors = new ArrayList<>();
        int t = Integer.parseInt(JOptionPane.showInputDialog("Quantos autores a pulicação tem?"));
        for(int i = 0 ; i < t ; i ++) {
            String nome = JOptionPane.showInputDialog("Nome do autor : " + (t-i)+" faltando");
            if(collabs.containsKey(nome)) {
            authors.add(nome);
            } else {
                i--;
                JOptionPane.showMessageDialog(null,"Este Colaborador não existe");
            }
        }
        String dec = JOptionPane.showInputDialog("Diga o conteudo da Publicação");
        Publicação nova = new Publicação(dec,authors);
        this.publications.add(nova);
        for(int i = 0 ; i < authors.size();i++) {
            collabs.get(authors.get(i)).addPub(nova);
        }
      }
      catch(NumberFormatException e) {
          JOptionPane.showMessageDialog(null,"Número inválido");
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String prof = JOptionPane.showInputDialog("Nome do professor :");
       if(collabs.containsKey(prof)&&collabs.get(prof).getClass().equals(Professor.class)) {
       String alu = JOptionPane.showInputDialog("Nome do aluno");
       if(collabs.containsKey(alu)&&!collabs.get(alu).getClass().equals(Professor.class)) {
       this.orientations.add("professor "+prof + ", aluno : "+ alu);
       ((Professor)collabs.get(prof)).addOrientation(alu);
       }else {
           JOptionPane.showMessageDialog(null,"Este aluno não existe");
       }
       } else {
           JOptionPane.showMessageDialog(null,"Este professor não existe");
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String nome = JOptionPane.showInputDialog("Nome do Projeto");
        int index = this.search_project(nome);
        if(index!=-1) {
            JOptionPane.showMessageDialog(null,projects.get(index).toString() );
        }else {
            JOptionPane.showMessageDialog(null,"Este projeto não existe");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nome = JOptionPane.showInputDialog("Nome do Colaborador");
        if(this.collabs.containsKey(nome)) {
            Colaborador col = collabs.get(nome);
            JOptionPane.showMessageDialog(null,col.toString());
        } else {
            JOptionPane.showMessageDialog(null,"Este colaborador não existe");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdSysGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdSysGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdSysGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdSysGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdSysGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
